spring:
  application:
    name: server-zipkin
  ##use rabbitmq
  sleuth:
    sampler:
      percentage: 1.0
    enabled: true
  rabbitmq:
    host: 192.168.173.150
    port: 5672
    username: test
    password: test
    publisher-confirms: true
    virtual-host: tms
  ##dataSource
  datasource:
#    schema: classpath:/mysql.sql
    name: kobe
    url: jdbc:mysql://192.168.158.111:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=true
    username: root
    password: 123456
    initialize: true
    continueOnError: true
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9411
##zipkin
zipkin:
  storage:
    type: mysql
